import { Router } from "express";
import PDFDocument from "pdfkit";
import User from "../models/User.js";
import HealthProfile from "../models/HealthProfile.js";
import SymptomLog from "../models/SymptomLog.js";
import Prediction from "../models/Prediction.js";
import authMiddleware from "../middleware/authMiddleware.js";

const router = Router();
router.use(authMiddleware);

// GET /api/report/generate — generate PDF health report
router.get("/generate", async (req, res) => {
  try {
    const user = await User.findById(req.user.id);
    const profile = await HealthProfile.findOne({ userId: req.user.id });
    const recentLogs = await SymptomLog.find({ userId: req.user.id }).sort({ createdAt: -1 }).limit(10);
    const latestPrediction = await Prediction.findOne({ userId: req.user.id }).sort({ createdAt: -1 });

    const doc = new PDFDocument({ margin: 50 });

    // Set response headers
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename=NoRog_Health_Report_${user.name.replace(/\s+/g, "_")}.pdf`);

    doc.pipe(res);

    // Header
    doc.fillColor("#2563eb").fontSize(26).text("NoRog Health Intelligence Report", { align: "center" });
    doc.moveDown();
    doc.fillColor("#4b5563").fontSize(12).text(`Generated on: ${new Date().toLocaleString()}`, { align: "center" });
    doc.moveDown(2);

    // Patient Info
    doc.fillColor("#1f2937").fontSize(18).text("Patient Information");
    doc.rect(doc.x, doc.y, 500, 1).fill("#e5e7eb");
    doc.moveDown(0.5);
    doc.fontSize(12).fillColor("#374151");
    doc.text(`Name: ${user.name}`);
    doc.text(`Email: ${user.email}`);
    doc.text(`Age: ${user.age || "N/A"}`);
    doc.text(`Gender: ${user.gender || "N/A"}`);
    doc.text(`Location: ${user.location?.city || "Unknown"}, ${user.location?.country || "Unknown"}`);
    doc.moveDown(1.5);

    // Health Snapshot
    doc.fontSize(18).fillColor("#1f2937").text("AI Health Assessment");
    doc.rect(doc.x, doc.y, 500, 1).fill("#e5e7eb");
    doc.moveDown(0.5);
    if (latestPrediction) {
      doc.fontSize(14).fillColor(latestPrediction.healthScore > 70 ? "#059669" : "#dc2626").text(`Overall Health Score: ${latestPrediction.healthScore}/100`);
      doc.fontSize(12).fillColor("#374151").text(`Trend: ${latestPrediction.trend.toUpperCase()}`);
      doc.moveDown(0.5);
      doc.text("Summary:", { underline: true });
      doc.text(latestPrediction.summary);
      doc.moveDown();
      doc.text("Key Identified Risks:", { underline: true });
      latestPrediction.risks.forEach(risk => {
        doc.text(`• ${risk.disease} (${risk.confidence}% confidence) - Urgency: ${risk.urgency}`);
      });
    } else {
      doc.text("No AI assessment data available yet.");
    }
    doc.moveDown(1.5);

    // Medical Conditions
    doc.fontSize(18).fillColor("#1f2937").text("Known Conditions & History");
    doc.rect(doc.x, doc.y, 500, 1).fill("#e5e7eb");
    doc.moveDown(0.5);
    doc.fontSize(12).fillColor("#374151");
    doc.text(`Medical History: ${profile?.medicalHistory?.join(", ") || "None reported"}`);
    doc.moveDown(0.5);
    doc.text("Family History:");
    if (profile?.familyHistory && profile.familyHistory.length > 0) {
      profile.familyHistory.forEach(item => {
        doc.text(`• ${item.relation}: ${item.condition}`);
      });
    } else {
      doc.text("None reported");
    }
    doc.moveDown(1.5);

    // Recent Symptoms
    doc.fontSize(18).fillColor("#1f2937").text("Recent Symptom Logs");
    doc.rect(doc.x, doc.y, 500, 1).fill("#e5e7eb");
    doc.moveDown(0.5);
    if (recentLogs.length > 0) {
      recentLogs.forEach(log => {
        const date = new Date(log.createdAt).toLocaleDateString();
        doc.fontSize(11).fillColor("#1f2937").text(`${date} - Severity: ${log.severity}/10`, { continued: true });
        doc.fillColor("#4b5563").text(` | Symptoms: ${log.symptoms.join(", ")}`);
        if (log.notes) doc.fontSize(10).text(`  Notes: ${log.notes}`);
        doc.moveDown(0.5);
      });
    } else {
      doc.text("No recent symptoms logged.");
    }

    // Footer
    const pageCount = doc.bufferedPageRange().count;
    for (let i = 0; i < pageCount; i++) {
        doc.switchToPage(i);
        doc.fontSize(8).fillColor("#9ca3af").text(
            "Disclaimer: This report is generated by an AI and is for informational purposes only. Consult a medical professional for diagnosis.",
            50,
            doc.page.height - 50,
            { align: "center", width: 500 }
        );
    }

    doc.end();
  } catch (error) {
    console.error("Report generation error:", error);
    res.status(500).json({ success: false, error: "Failed to generate report" });
  }
});

export default router;